### ISSUE TITLE
Description field includes address

### ISSUE THREAD

**Issue by henare** [43South/HuonValleyDA#1]
It should just include the description.

**Comment by henare** [comment]
This might be useful: http://php.net/manual/en/function.explode.php

**Comment by 43South** [comment]
Yeah, I know, they put the address in the description again, as well as in a separate address field. I can split it out but sometimes there's an additional field delimited by ' - ' within the description. I was lazy and left it as they publish it. I'll snip it off and commit again.

**Comment by henare** [comment]
> I can split it out but sometimes there's an additional field delimited by ' - ' within the description.

:+1: make sure this case is covered too then.

**Comment by 43South** [comment]
I've done by best to take out the address if it's there. Sometimes it's necessary, as it's something like 'land to the south of ...' so the address isn't the actual address. The address has erratic Tasmania or Tasmania, Australia on the end. I trim this and standardise to Tasmania.
