### ISSUE TITLE
Don't overwrite existing records on repeat scrapes

### ISSUE THREAD

**Issue by henare** [43South/HuonValleyDA#2]
Otherwise each day the `date_scraped` on every record will be updated.

That's what this code is for: https://github.com/planningalerts-scrapers/KingboroughCouncil/commit/8673e9fcf0026bbc03bc9335416b86a707234a83

**Comment by 43South** [comment]
Thanks Henare, I realised what the code was for but couldn't get it to work when I was testing locally, the version of scraperwiki that I downloaded didn't have a select method, so it failed with an error. I'll put it back in and test again on morph.io. (I commented it out in the Kingborough scraper too.)

**Comment by henare** [comment]
Sounds good :bouquet:

**Comment by 43South** [comment]
I've put in the 'don't overwrite' code. Weirdly, when I run it in morph.io it both adds the records and says that it's not going to. Perhaps it's a peculiarity of morph.io.
